### ISSUE TITLE
ghminer.graphql and ghminer.json not found when running with asdf

### ISSUE THREAD

**Issue by nileshtrivedi** [h1alexbel/ghminer#59]
I use [asdf](https://asdf-vm.com/) to manage various NodeJS versions. Running `ghminer` as instructed in the README gives me this error:

```
~/code/js/ghminer » node -v                                                                                                                      mac@workbox
v20.11.0
-------------------------------------------------------------------------------------------------------------------------------------------------------------
~/code/js/ghminer » npm -v                                                                                                                       mac@workbox
10.2.4
-------------------------------------------------------------------------------------------------------------------------------------------------------------
~/code/js/ghminer » which ghminer                                                                                                                mac@workbox
/Users/mac/.asdf/shims/ghminer
-------------------------------------------------------------------------------------------------------------------------------------------------------------
~/code/js/ghminer » ghminer --query "stars:100000..2000000" --start "2005-01-01" --end "2024-10-01" --tokens pats.txt                            mac@workbox
Running ghminer@0.0.7
Compiled search query: stars:100000..2000000 created:2005-01-01..2024-10-01
Total results: 54
Error: ENOENT: no such file or directory, open 'ghminer.graphql'
    at Object.readFileSync (node:fs:453:20)
    at graph (/Users/mac/.asdf/installs/nodejs/20.11.0/lib/node_modules/ghminer/src/graph.js:27:13)
    at fetchResultsBatch (/Users/mac/.asdf/installs/nodejs/20.11.0/lib/node_modules/ghminer/src/index.js:103:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'ghminer.graphql'
}
Error: ENOENT: no such file or directory, open 'ghminer.json'
    at Object.readFileSync (node:fs:453:20)
    at writeFiles (/Users/mac/.asdf/installs/nodejs/20.11.0/lib/node_modules/ghminer/src/index.js:234:32)
    at /Users/mac/.asdf/installs/nodejs/20.11.0/lib/node_modules/ghminer/src/index.js:263:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'ghminer.json'
}
```

**Comment by h1alexbel** [comment]
@nileshtrivedi as [README states](https://github.com/h1alexbel/ghminer?tab=readme-ov-file#graphql-query), `ghminer` requires you to provide `ghminer.graphql` as query to GitHub Graphql API, and `ghminer.json` as mapping schema for output parsing. Both files should be located in the directory, where you run `ghminer`:

`ghminer.graphql`:

```graphql
query ($searchQuery: String!, $first: Int, $after: String) {
  search(query: $searchQuery, type: REPOSITORY, first: $first, after: $after) {
    repositoryCount
    nodes {
      ... on Repository {
        nameWithOwner
        defaultBranchRef {
          name
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
```

`ghminer.json`:

```json
{
  "repo": "nameWithOwner",
  "branch": "defaultBranchRef.name"
}
```

Now, you should be able to run your query:

```bash
ghminer --query "stars:>10 language:c size:>=20 mirror:false template:false" --start "2024-06-01" --end "2024-06-02" --tokens "$PATS"
```

I got this results:

```csv
repo,branch
cnlohr/minimdnsd,master
medcelerate/FFGLTouchEngine,master
astledsa/Deep-Learning-C,main
henriquesebastiao/saturn,main
attackevals/ael,main
ty2/ideapad-laptop-tb2024g6plus,main
mattsta/datakit,main
WeActStudio/WeActStudio.USB2CANFDV1,master
ywnico/vitaki-fork,ywnico
ADM42/adm42,main
```

**Comment by h1alexbel** [comment]
@nileshtrivedi for more complicated example, check out this repo: https://github.com/h1alexbel/sr-detection. It has both: `ghminer.graphql` and `ghminer.json`

**Comment by nileshtrivedi** [comment]
Thanks @h1alexbel 

I was just following the command given in the [How To Use](https://github.com/h1alexbel/ghminer?tab=readme-ov-file#how-to-use) section and did not notice that these parameters were specifieded as required. I am able to fetch the results now. 👍

**Comment by h1alexbel** [comment]
@h1alexbel great. thanks for reporting!
